### ISSUE TITLE
Problem with [url]

### ISSUE THREAD

**Issue by tomaszchabinka** [jarrett/rbbcode#18]
Hi, I notice problem with [url] mark. I'm using gem 'rails', '3.2.14' and gem 'rbbcode', '~> 1.0.3'. 

When I have some @group.description with [url] mark (like [url="http://facebook.com/projekt.polska.wroclaw"]Koło Wrocław na Facebooku[/url]) I get from 
RbbCode.new.convert(@group.description) &lt;p&gt;\* &lt;a href=&quot;&quot;&gt;Koło Wrocław na Facebooku&lt;/a&gt;&lt;/p&gt;

**Comment by jarrett** [comment]
I don't recall why I reopened this issue. It was probably in error. I'm closing it for now.
